### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by ArtificalAbsolute** [SirHamburger/ArtifactOfDoom#2]
Please add to Tougher Times (impossible play because of burning) capability block trigger (but for balance u can add count of bears to formula). Also i think that more interesing if change formula from <(totalItems - currentStage * averageItemsPerStage) ^ exponentTriggerItems> to <SomeDamage(#10 for example)*minutes - currentStage * averageItemsPerStage * difficulty(#1/2/3) ^ exponentTriggerItems> it will be more like how Artifact of Sacrifice works

Sorry for my language

**Comment by SirHamburger** [comment]
Thanks for your feedback.

Tougher Times was always planed that it works. But i made a programming mistake so it didn't. I'll release a patch soon.

I don't understand your formular at the moment. 
For exaple you are on stage 1 with averageItems 5 and difficulty is monsoom (3) and the exponentTriggerItems would be 2.
Then you would have:
`(100-1*5*3)^2=7225`
So you would need to kill 7225 enemies for gaining the first item?

As far as i know the artifact of sacrifice has a base chance for every enemie and an increased chance if that enemie is an elite. The biggest issue i had was to find a formular where you get quite strong soon but not to strong that the game is autoplay.

**Comment by ArtificalAbsolute** [comment]
>Then you would have:
(100-1*5*3)^2=7225
So you would need to kill 7225 enemies for gaining the first item?

ops.It was just a form of speech. I don't know much about balance, it was just an idea.
Seriously though, it should be like
(100#damage * (minutes+1)^2 - (stage * averageitems * difficulty)^2) = taken damage to monsters for gaining the item
0 minutes
`100*1-(1*3*3)^2 = 9`
5 minutes
`100*25-(1*3*3)^2 = 2419`
40 minutes
`100*40^2 - (1*10*3)^2 = 159 100‬‬` dmg for 1 item
if we want to farm on 1 stage
`100*40^2 - (7*10*3)^2 = 115 900‬‬`
for default game
`100*40^2 - (11*10*3)^2 = 51 100‬`
for speedrunner 

this formula doesn't give many advantages for speedrunner and for Artifact of Swarms and doesn't forgive the loss of items but whatever requires improvements. Also this formula can break for super fast speedrunner on moonsoon

also u can enchant your formula but pls add nerf for artifact of swarms and less chance for comeback for people who lost their items

**Comment by SirHamburger** [comment]
I'm not sure if the trigger should be the damage you make since you can have luck and get and dagger in the first map and get many items or you get only defence items and don't do that much damage. 

I'll think about it and maybe add the possibility to use such a formular.

The artifact of swarm is a bit of high risk high reward since its often not possible to doge all of the attacks. But due to the exponental increase of enemies you've to kill i don't see a too big problem since you can't farm forever (maybe except for engeneer :D)

If you want a lesser chance for comebacks just reduce the amount of averageItemsPerStage maybe to 0. But then you should also set the exponentTriggerItems to a lesser value (maybe 1.5). But then you'll soon need many kills to get an item.

I've some questions for you since i don't play that often:
1. On which difficulty do you play?
2. Did you try other difficulties?
3. Do you think that it's too easy?
4. Do you think that the loose of items is fair/unfair?
5. Do you always/never/sometimes "win" the run?
6. Did you change any settings?
7. Do you wish more settings (like min enemies to get an item)?
8. Did you've any other bugs?

maybe we can also meet in discord an talk a little bit.

**Comment by ArtificalAbsolute** [comment]
1. - only moonsoon but for test this mode and another i run short game for test
2. - only for test ~1-1.5 hour
3. - It's too easy if u play with artifact of glass + artifact of swarm
4. - FAIR (becouse i play with artifact of sacrafice :D)
5. - If my character have blink or another way to fast moving i win often (playing for artificer so impossible and i don't check but think that for REX too)
6. - Nope but for fair if u play with artifact of glass need to heavier settings
7. - For more difficult and challenging game it would be nice to disable advantage when losing an item but only if u want to set up this setting, not default
8. - no

My idea for the mod is that the chance to get an item doesn't depend on anything other than the number of mobs killed and their type. Then whatever I do I don't get advantages. And that's fair

@chlebuSShek#5880

**Comment by SirHamburger** [comment]
Hello,
the new version with advaced settings i now released. 
If you've any other ideas or find any bugs feel free to reopen this issue or open a new one.
